apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-platform

commonLabels:
  app.kubernetes.io/name: devops-platform-app
  app.kubernetes.io/part-of: devops-platform
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - deployments/app.yaml
  - services/app.yaml
  - configmaps/app.yaml
