apiVersion: v1
kind: Namespace
metadata:
  name: devops-platform
  labels:
    app.kubernetes.io/name: devops-platform
    app.kubernetes.io/part-of: devops-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
